# name: DEPLOY PULL REQUEST.

# on: [pull_request]

# jobs:
#   deploy:
#     name: Deploy.
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: npm install surge
#       - run: bash ./auto.sh ${GITHUB_REF} ${{ secrets.SURGE_TOKEN }}

name: DEPLOY PULL REQUEST

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.comment.user.login }}