name: DEPLOY PULL REQUEST.

on: [pull_request]

jobs:
  deploy:
    name: Deploy.
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install surge
      - run: bash ./surge_login.sh ${{ secret.EMAIL }} ${{ secret.PASSWORD }}
      - run: bash ./auto.sh ${GITHUB_REF}
