# name: DEPLOY PULL REQUEST.

# on: [pull_request]

# jobs:
#   deploy:
#     name: Deploy.
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: npm install surge
#       - run: bash ./auto.sh ${GITHUB_REF} ${{ secrets.SURGE_TOKEN }}

name: DEPLOY PULL REQUEST

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - uses: gr2m/git-checkout-pull-request-action@master
      - run: node verify ${{ github.event.action }} ${{ github.event.comment.user.login }} ${{ github.event.comment.body }}
      - run: npm install surge @actions/github
      - run: bash ./auto.sh ${{ github.event.issue.pull_request.url }} ${{ secrets.SURGE_TOKEN }}
      - run: node ./spawn_comment.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.pull_request.url }}